# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
